spring:

  application:
    name: muse-backend

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver

  kafka:
    producer:
      acks: all
    streams:
      security:
        protocol: SASL_SSL
      properties:
        sasl.mechanism: PLAIN
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate

  threads:
    virtual:
      enabled: true

custom:
  kafka:
    http:
      url:
        port: 8080
